# Generated by Django 5.1.6 on 2025-03-28 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0009_task_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subtask',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subtask',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='subtask',
            unique_together={('title', 'deadline', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('title', 'deadline', 'owner')},
        ),
    ]
