# Generated by Django 5.1.6 on 2025-03-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0010_alter_subtask_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('blocked', 'Blocked'), ('done', 'Done')], max_length=20, null=True),
        ),
    ]
